services:
  bot:
    build: .
    container_name: lifemanager-bot
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15
    container_name: lifemanager-db
    ports:
      - 5449:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

  redis:
    image: redis:7
    container_name: lifemanager-redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data:
